language: generic
sudo: required
matrix:
  include:
    - services:
        - docker
      script: docker run -v $PWD:/ga greenaddress/ci@sha256:48e8d7976e3b1f94dc863ac4d5029f762d84eb3214fa9d819e3e2f2302a94f39 /bin/sh -c "cd /ga && tools/bionic_deps.sh && ./tools/travisdotter.sh && ./tools/builddeps.sh"
